### ISSUE TITLE
use cuda for prediction

### ISSUE THREAD

**Issue by giangtranducts** [unilight/sheet#2]
May you guide me to use predict in cuda for better performance? Thanks a lot
(https://github.com/unilight/sheet?tab=readme-ov-file#i-just-want-to-use-your-trained-mos-predictor)

**Comment by sh-lee-prml** [comment]
```
    ssl_mos_predictor = torch.hub.load("unilight/sheet:v0.1.0", "default", trust_repo=True, force_reload=True)
    ssl_mos_predictor.model.cuda()

    result= ssl_mos_predictor.predict(wav=torch.rand(16000).cuda())
```

I modified the code for CUDA. Try to use this :)

**Comment by giangtranducts** [comment]
Thank a lot @sh-lee-prml sh

**Comment by unilight** [comment]
@sh-lee-prml Thanks a lot! I will modify the readme with your suggestion :)
